apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hpa
  template:
    metadata: 
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: img-deployment
        ports:
          - containerPort: 8000

        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
